In [1]:
import gym
import gym_ttt
import numpy as np


def main():
    env = gym.make("TTT-v0")
    done = False
    # reward of the whole episode
    episode_reward = 0
    n_steps = 0
    # get the initial state of the environment
    state = env.reset()
    while not done:
        action, n_free_pos = env.sample()
        next_state, reward, done, info = env.step(action)
        episode_reward += reward
        state = next_state
        n_steps += 1
    print(state)
    print(
        "episode_reward:", episode_reward,
        "\tn_steps:", n_steps)


if __name__ == "__main__":
    main()



[[0 0 0]
 [0 0 0]
 [0 0 0]]
episode_reward: 0 	n_steps: 5


In [11]:
%run main.py


[[1 0 0]
 [0 0 0]
 [0 0 0]]
episode_reward: 0 	n_steps: 5
